name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo check
        run: cargo check --all-targets
      - name: Cargo test
        run: cargo test --all-targets
